# Generated by Django 5.0.7 on 2024-10-12 23:10

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDI',
            fields=[
                ('id', models.CharField(default=api.models.generate_unique_id, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('G', 'Gastronomía'), ('E', 'Entretenimiento'), ('AL', 'Aire libre'), ('M', 'Música'), ('C', 'Cine'), ('A', 'Artesanías')], max_length=15)),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=20, validators=[api.models.validate_password_length])),
                ('es_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('pdi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.pdi')),
            ],
            bases=('api.pdi',),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('pdi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.pdi')),
                ('dia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('horaInicio', models.IntegerField()),
                ('minutoInicio', models.IntegerField()),
                ('duracion', models.IntegerField()),
            ],
            bases=('api.pdi',),
        ),
    ]
